import Head from "next/head";
import Components from "../components/basic/AllComponents";

export default function Basic() {
  return (
    <div>
      <Head>
        <title>Basic Components - Free Nextjs Ui Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/probby_logo.png" />
      </Head>
      <Components />
    </div>
  );
}
